version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_semantic_search
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  tei-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: tei-server
    command: --model-id BAAI/bge-m3
    ports:
      - "8080:80"
    volumes:
      - tei-data:/data
    restart: unless-stopped

volumes:
  tei-data:
